In [3]:
from __future__ import print_function
import torch
import numpy as np

In [2]:
x = torch.Tensor(5, 3)
print(x)


 0.0000e+00  1.0842e-19  0.0000e+00
 1.0842e-19  3.4126e+21  6.7354e+22
 5.3240e+22  1.7089e-04  1.3532e+22
 3.3828e+21  1.3385e+22  8.3656e+20
 4.1726e-08  4.1958e-08  0.0000e+00
[torch.FloatTensor of size 5x3]



In [4]:
x = torch.rand(5,3)
print(x)


 0.9466  0.3344  0.5593
 0.0146  0.3131  0.7167
 0.2614  0.7045  0.8013
 0.0003  0.0854  0.3774
 0.5715  0.5190  0.7079
[torch.FloatTensor of size 5x3]



In [5]:
print(x.size())

torch.Size([5, 3])


In [7]:
y = torch.rand(5,3)
print(x+y)


 1.5190  1.3274  1.5313
 0.8087  1.2369  1.6621
 0.8016  1.2536  1.0011
 0.9035  1.0558  1.2958
 1.0483  1.5103  1.2616
[torch.FloatTensor of size 5x3]



In [8]:
print(torch.add(x,y))


 1.5190  1.3274  1.5313
 0.8087  1.2369  1.6621
 0.8016  1.2536  1.0011
 0.9035  1.0558  1.2958
 1.0483  1.5103  1.2616
[torch.FloatTensor of size 5x3]



In [14]:
result = torch.Tensor(5,3)
torch.add(x,y,out=result)
print(result)


 1.5190  1.3274  1.5313
 0.8087  1.2369  1.6621
 0.8016  1.2536  1.0011
 0.9035  1.0558  1.2958
 1.0483  1.5103  1.2616
[torch.FloatTensor of size 5x3]



In [15]:
y.add_(x)
print(y)


 1.5190  1.3274  1.5313
 0.8087  1.2369  1.6621
 0.8016  1.2536  1.0011
 0.9035  1.0558  1.2958
 1.0483  1.5103  1.2616
[torch.FloatTensor of size 5x3]



In [16]:
print(x[:,1])


 0.3344
 0.3131
 0.7045
 0.0854
 0.5190
[torch.FloatTensor of size 5]



In [20]:
a = torch.ones(5)
b = a.numpy()
print(a)
print(b)


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]

[ 1.  1.  1.  1.  1.]


In [21]:
a.add_(1)
print(a)
print(b)


 2
 2
 2
 2
 2
[torch.FloatTensor of size 5]

[ 2.  2.  2.  2.  2.]


In [25]:
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1,out=a)
b.add_(2)
print(b)
print(a)


 4
 4
 4
 4
 4
[torch.DoubleTensor of size 5]

[ 4.  4.  4.  4.  4.]


In [30]:
from torch.autograd import Variable

In [49]:
x = Variable(torch.ones(2,2), requires_grad=True)
print(x)

Variable containing:
-0.3053 -0.6536
-0.0894 -0.0897
[torch.FloatTensor of size 2x2]



In [65]:
y = x+2
print(y)

Variable containing:
 3
 3
 3
[torch.FloatTensor of size 3]



In [66]:
print(y.grad_fn)

In [67]:
z = y*y*3
out = z.mean()
print(z,out)

Variable containing:
 27
 27
 27
[torch.FloatTensor of size 3]
 Variable containing:
 27
[torch.FloatTensor of size 1]



In [68]:
out.backward()
print(x.grad)

Variable containing:
 6
 6
 6
[torch.FloatTensor of size 3]



In [86]:
x = torch.ones(3)
x = Variable(x, requires_grad = True)
y = x*2
print(y)

Variable containing:
 2
 2
 2
[torch.FloatTensor of size 3]



In [87]:
gradients = torch.FloatTensor([0.1,0.11,1])
print(gradients)
y.backward(gradients)
print(x.grad)


 0.1000
 0.1100
 1.0000
[torch.FloatTensor of size 3]

Variable containing:
 0.2000
 0.2200
 2.0000
[torch.FloatTensor of size 3]



In [142]:
a = Variable(torch.ones(5))
b = a.data.numpy()
print(b)

[ 1.  1.  1.  1.  1.]


In [171]:
first_tensor = Variable(torch.FloatTensor([1.2,2.2]))
second_tensor = torch.FloatTensor([0.0])
third_tensor = torch.cat((first_tensor, second_tensor), 0)
print(third_tensor)

Variable containing:
 1.2000
 2.2000
 0.0000
[torch.FloatTensor of size 3]



In [169]:
a = Variable(torch.ones(4))
b = Variable(torch.ones(4))
c = torch.log(torch.exp(a))
print(c)

Variable containing:
 1.0000
 1.0000
 1.0000
 1.0000
[torch.FloatTensor of size 4]

